version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - landmanagementnet

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/landmanagement
      - JWT_SECRET=your_jwt_secret
    networks:
      - landmanagementnet

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"
    networks:
      - landmanagementnet

networks:
  landmanagementnet:
    driver: bridge
