version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: landmanagement
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    environment:
      MONGO_URI: mongodb://admin:adminpassword@mongo:27017/landmanagement?authSource=admin
      JWT_SECRET: secret_key
    ports:
      - 5001:5001
    depends_on:
      - mongo
    volumes:
      - ./backend:/tmp/app
      

  frontend:
    build: ./frontend
    ports:
      - 8080:80
    depends_on:
      - backend

volumes:
  mongo-data:
